### PR TITLE
Update @octokit/rest.js dependency

### PR DESCRIPTION
**Pull request by froi**
# Pull Request Template

Thank you for your contribution!

Before submitting this Pull Request, please make sure that a similar [Pull Request](https://github.com/gsa/code-gov-integrations/pulls) does not exist.

## Description

The version of `@octokit/rest` that was in use was behind on some major updates to the package's API. The new version has more descriptive functions and solves some `npm audit` issues.

In addition the `@octokit/plugin-throtteling` implements Github's recommended best practices for rate limit and abuse limit handling. This will help the project interact better with Github as a whole.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x]  Dependency and test update 

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran and updated project test suite.
   
image

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by froi** [comment]
Friendly ping @saracope 😄

**Comment by saracope** [comment]
Pinging @bjbhatt for review.

**Comment by froi** [comment]
Any update on this?

**Comment by seanstar12** [comment]
@froi merging into branch here for testing. Found an issue on `libs/github/utils.js` that I will correct.

**Pull request merged**
